### ISSUE TITLE
Update API documentation

### ISSUE THREAD

**Issue by tiyash-basu-frequenz** [frequenz-floss/frequenz-api-microgrid#127]
### What's needed?

The API documentation needs to be updated, to expand it, and make it consistent with proposed updates in other Frequenz APIs. Refer to https://github.com/frequenz-floss/frequenz-api-dispatch/issues/60 and https://github.com/frequenz-io/api-weather-spec/issues/6 for the documentation style.

**Comment by llucax** [comment]
When writing docs, I strongly recommend trying out how it is rendered doing before merging stuff:

```sh
pip install -e .[dev-mkdocs]
mkdocs serve
```

Remember Markdown is used.
