### ISSUE TITLE
Scan dependencies for vulnerabilities

### ISSUE THREAD

**Issue by leandro-lucarella-frequenz** [frequenz-floss/frequenz-api-microgrid#15]
### What's needed?

We need to check dependencies for vulnerabilities, so we can update the minimum requirements to non-vulnerable versions.

### Proposed solution

We have several options we can check:

* [pip-audit](https://github.com/pypa/pip-audit) audits Python environments and dependency trees for known vulnerabilities.
* [Safety](https://github.com/pyupio/safety) checks Python dependencies for known security vulnerabilities and suggests the proper remediations for vulnerabilities detected. It seems to be a paid service with only free tiers for non-commercial project.
* [Dependabot](https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates) is a GitHub alternative

**Comment by tiyash-basu-frequenz** [comment]
We use dependabot now.
Can be closed.
