### ISSUE TITLE
Set up repo for reporting client

### ISSUE THREAD

**Issue by cwasicki** [frequenz-floss/frequenz-api-microgrid#216]
The python client should be located in its own repository, which needs to be set up:
* Create new repo `frequenz-client-reporting-python` (according to https://github.com/frequenz-floss/frequenz-sdk-python/wiki/APIs-stack-and-repositories-structure)
* Configure the repo using repo config as described here: https://frequenz-floss.github.io/frequenz-repo-config-python/

**Comment by cwasicki** [comment]
This PR for the microgrid API client can be used as a reference: https://github.com/frequenz-floss/frequenz-client-microgrid-python/pull/1.

**Comment by tiyash-basu-frequenz** [comment]
Why is this issue in this repo?
