### ISSUE TITLE
Publish API documentation

### ISSUE THREAD

**Issue by leandro-lucarella-frequenz** [frequenz-floss/frequenz-api-microgrid#22]
### What's needed?

A proper place where API documentation can be easily accessed.

### Proposed solution

There are several options:

* GitHub pages.
* Publish on every run to the Wiki.
* Some hosted services: https://blog.gendocu.com/posts/documenting-grpc/.

Long term GitHub pages is probably the best option, if we have some sort of project website.

### Alternatives and workarounds

Read the docs from the source code.

### Additional context

Follow-up on #18.

**Comment by tiyash-basu-frequenz** [comment]
This issue could be considered related: https://github.com/frequenz-floss/frequenz-api-microgrid/issues/42

@llucax what is the status of this one? We are already publishing the documentation, right? Would it make sense add its to link it to the repo README as well? (readers may refer to #6)

**Comment by llucax** [comment]
Yes, this is done. There is always room for improvements but the docs are published now at https://frequenz-floss.github.io/frequenz-api-microgrid/.
