### ISSUE TITLE
Auto render API docs to HTML

### ISSUE THREAD

**Issue by tiyash-basu-frequenz** [frequenz-floss/frequenz-api-microgrid#42]
### What's needed?

Having auto-rendered HTML docs for the microgrid API would be nice to have, similar to the [SDK docs](https://frequenz-floss.github.io/frequenz-sdk-python/v0.19/).

### Proposed solution

The docs can be auto-rendered using plugins like https://github.com/pseudomuto/protoc-gen-doc.

The plugin mentioned above can be invoked like the following to render `index.html` with the inline protobuf documentation:
```bash
protoc --doc_out=. --doc_opt=html,index.html proto/*/*/*/*.proto -I proto -I submodules/api-common-protos  
```

Note that this plugin is already being used in the CI.

### Use cases

The primary use-case for this would be to help provide the API documentation in a more readily consumable manner. ATM people need to read inline docs to see how the API behaves.

**Comment by llucax** [comment]
API docs are rendered and published now at https://frequenz-floss.github.io/frequenz-api-microgrid/.
