### ISSUE TITLE
Use `Location` from the common specs

### ISSUE THREAD

**Issue by tiyash-basu-frequenz** [frequenz-floss/frequenz-api-microgrid#76]
### What's needed?

The `Location` message defined [here](https://github.com/frequenz-floss/frequenz-api-microgrid/blob/e48d52fb96536fc6bb9422c4b2ca666bcc1a6761/proto/frequenz/api/microgrid/microgrid.proto#L317-L323) should be removed, and instead the one from the common specs should be  used.

### Proposed solution

The following should be used from the common specs repo:
```proto
// A pair of geographical co-ordinates, representing the location of a place.
message Location { 
  // Latitude ranges from -90 (South) to 90 (North)
  float latitude = 1;

   // Longitude ranges from -180 (West) to 180 (East)
   float longitude = 2;
}
```

**Comment by thomas-nicolai-frequenz** [comment]
@tiyash-basu-frequenz I think we discussed that we might want to add the country code here as well, right?

```Patch
// A pair of geographical co-ordinates, representing the location of a place.
message Location { 
  // Latitude ranges from -90 (South) to 90 (North)
  float latitude = 1;

   // Longitude ranges from -180 (West) to 180 (East)
   float longitude = 2;
   
+   // Country ISO 3166-1 Alpha 2
+   string country_code = 3;
}
```

@stefan-brus-frequenz FYI

**Comment by tiyash-basu-frequenz** [comment]
> I think we discussed that we might want to add the country code here as well, right?

Yep, this PR was just intended to move the existing definition, but I can add another commit to the PR to add the country code.

The PR in the common repo was already merged though. I will make a new PR to add the country code.

**Comment by tiyash-basu-frequenz** [comment]
Was addressed in https://github.com/frequenz-floss/frequenz-api-microgrid/pull/99
