### ISSUE TITLE
Rename RPCs named as `StreamX` to `GetXStream`

### ISSUE THREAD

**Issue by tiyash-basu-frequenz** [frequenz-floss/frequenz-api-microgrid#84]
### What's needed?

`stream` as a verb refers to the act of publishing something. Therefore RPC names following the naming scheme `StreamX`, e.g., [`StreamComponentData`](https://github.com/frequenz-floss/frequenz-api-microgrid/blob/1abca32b1d0c62b5330aeecf1f38634f7c79a417/proto/frequenz/api/microgrid/microgrid.proto#L84), are ambigous. E.g., a client invoking `stream_component_data` could also indicate that the client intends to publish data, instead of consuming data from a stream.

### Proposed solution

A more appropriate name would be `GetXStream`. E.g., the RPC `StreamComponentData` could be renamed to `GetComponentDataStream`, removing any ambiguity in the intention of the method.

Edit:
The current consensus is to have `PublishX` methods to stream data, and `SubscribeX` methods to consume data from streams.

**Comment by llucax** [comment]
I see and agree that the ambiguity is not good, but I don't find `GetXStream` super clear either. Also the *sandwitch* approach seems like it could introduce some ambiguity itself, what if you want to stream an object that ends with *stream* itself. Like `GetRiverStreamStream`? I know is a far fetched example, but still it is noisy in my head :P

How would it be the name if we want to send data to the server? `PutXStream` / `PutComponentDataStream`? `PushXStream` / `PushComponentDataStream`?

Throwing out alternatives:

* `PullComponentData` / `PushComponentData`
* `StreamInComponentDataIn` / `StreamOutComponentData`
* `SubscribeComponentData` (or `ConsumeComponentData`) / `PublishComponentData`

**Comment by tiyash-basu-frequenz** [comment]
I was just about to suggest the subscribe/publish option :)

It sounds good to me.
